# Generated by Django 4.2.20 on 2026-01-15 02:50

import django.core.validators
from django.db import migrations, models
import sales_application.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SalesApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=20)),
                ('resume', models.FileField(help_text='Upload your resume in PDF format (max 5MB)', upload_to='resumes/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf']), sales_application.models.validate_pdf_file, sales_application.models.validate_file_size])),
                ('has_bachelors_degree', models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('in_progress', 'In Progress')], default='no', help_text='Select "In Progress" if currently enrolled', max_length=12, verbose_name="Do you have a bachelor's degree?")),
                ('degree_details', models.TextField(blank=True, help_text='If yes, please specify your degree, university, and graduation year', verbose_name='Degree Details (Optional)')),
                ('has_worked_sales_before', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=3, verbose_name='Have you worked in sales before?')),
                ('years_of_sales_experience', models.PositiveIntegerField(default=0, verbose_name='If yes, how many years of sales experience?')),
                ('previous_work_experience', models.TextField(blank=True, help_text='Please describe your previous work experience in detail')),
                ('educational_experience', models.TextField(blank=True, help_text='Please list your educational background and qualifications')),
                ('is_certified_sales_professional', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=3, verbose_name='Are you a certified sales professional?')),
                ('can_relocate', models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('maybe', 'Maybe, depending on opportunity')], max_length=5, verbose_name='Are you willing to relocate?')),
                ('has_own_vehicle', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=3, verbose_name='Do you have reliable transportation?')),
                ('cover_letter', models.TextField(blank=True, help_text='Optional: Include a cover letter or additional information')),
                ('application_date', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('reviewed', 'Reviewed'), ('shortlisted', 'Shortlisted'), ('rejected', 'Rejected'), ('hired', 'Hired')], default='pending', max_length=20)),
            ],
            options={
                'verbose_name': 'Sales Application',
                'verbose_name_plural': 'Sales Applications',
                'ordering': ['-application_date'],
            },
        ),
    ]
