"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 4.2.19.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv
load_dotenv()
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure--*)3pd+&c*76gnikyo^(rnz!ivf&iy!k1z4w$l(4!$ekc0*p$8')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    'topsoftware.tech', 
    'www.topsoftware.tech',
    'localhost',
    '127.0.0.1',
    '192.168.1.203',  # Your local IP address
    'topsoftware-website-1c184caef3c1.herokuapp.com',
]

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_recaptcha',
    
    # Local apps
    'contact',
    'home',
    'pricing',
    'portfolio',
    'payments',
    'sales_application',

    # Installed third-party apps
    'corsheaders',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    "config.middleware.EnforceDomainMiddleware"
]

CSRF_TRUSTED_ORIGINS = [
    "https://www.topsoftware.tech",
    "http://localhost:8000",
    "http://127.0.0.1:8000"
]
CSRF_COOKIE_SECURE = not DEBUG  # Only use secure cookies in production

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(BASE_DIR, 'navigationmain'),
            os.path.join(BASE_DIR, 'home', 'templates'),
            os.path.join(BASE_DIR, 'contact', 'templates'),
            os.path.join(BASE_DIR, 'pricing', 'templates'),
            os.path.join(BASE_DIR, 'portfolio', 'templates'),
            os.path.join(BASE_DIR, 'payments', 'templates'),
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
    os.path.join(BASE_DIR, 'home', 'static'),
    os.path.join(BASE_DIR, 'contact', 'static'),
    os.path.join(BASE_DIR, 'pricing', 'static'),
    os.path.join(BASE_DIR, 'portfolio', 'static'),
    os.path.join(BASE_DIR, 'payments', 'static'),
]

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Email Configuration - Using Environment Variables for Security
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = "officialtopsoftware@gmail.com"
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', "")

# Square Configuration
SQUARE_LOCATION_ID = os.getenv('SQUARE_LOCATION_ID', "")

# CORS Settings
CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_METHODS = ["GET", "POST", "OPTIONS", "PUT", "DELETE"]
CORS_ALLOWED_ORIGINS = [
    "http://localhost:8000",
    "http://127.0.0.1:8000",
]

# Stripe Settings - Using Environment Variables for Security
STRIPE_PUBLISHABLE_KEY = os.getenv('STRIPE_PUBLISHABLE_KEY', '')
STRIPE_SECRET_KEY = os.getenv('STRIPE_SECRET_KEY', '')
STRIPE_WEBHOOK_SECRET = os.getenv('STRIPE_WEBHOOK_SECRET', '')

# reCAPTCHA Settings - Using Environment Variables for Security
RECAPTCHA_PUBLIC_KEY = os.getenv('RECAPTCHA_PUBLIC_KEY', '')
RECAPTCHA_PRIVATE_KEY = os.getenv('RECAPTCHA_PRIVATE_KEY', '')
RECAPTCHA_DOMAIN = 'www.recaptcha.net'

# Media files (Uploaded files)
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

FILE_UPLOAD_MAX_MEMORY_SIZE = 5242880  # 5MB
FILE_UPLOAD_PERMISSIONS = 0o644
FILE_UPLOAD_HANDLERS = [
    'django.core.files.uploadhandler.MemoryFileUploadHandler',
    'django.core.files.uploadhandler.TemporaryFileUploadHandler',
]

# Backblaze B2 Configuration
# Application Key ID: 0046d1240f581bd0000000002
# Key Name: resumekey
# Bucket Name: topsoftwareresumes
# Bucket ID: 062de1c28440bff598b10b1d
B2_ACCESS_KEY = os.getenv('B2_ACCESS_KEY', '0046d1240f581bd0000000002')
B2_SECRET_KEY = os.getenv('B2_SECRET_KEY', 'K0043sViXRC/ec6tic5m23VkoQiAZU8')
B2_BUCKET_NAME = os.getenv('B2_BUCKET_NAME', 'topsoftwareresumes')

# Only configure B2 if credentials are provided
USE_B2_STORAGE = bool(B2_ACCESS_KEY and B2_SECRET_KEY)

if USE_B2_STORAGE:
    # Add storages to INSTALLED_APPS if using B2
    if 'storages' not in INSTALLED_APPS:
        INSTALLED_APPS.append('storages')
    
    # AWS/B2 Settings
    AWS_ACCESS_KEY_ID = B2_ACCESS_KEY
    AWS_SECRET_ACCESS_KEY = B2_SECRET_KEY
    AWS_STORAGE_BUCKET_NAME = B2_BUCKET_NAME
    
    # Backblaze B2 endpoint (choose based on your region)
    # Note: B2 uses S3-compatible API, but endpoint format is different
    # The endpoint should NOT include the bucket name
    AWS_S3_ENDPOINT_URL = 'https://s3.us-west-002.backblazeb2.com'  # US West
    # Alternative regions:
    # US West: s3.us-west-002.backblazeb2.com
    # US East: s3.us-east-005.backblazeb2.com
    # EU Central: s3.eu-central-003.backblazeb2.com
    
    # Optional: Use custom domain for CDN (for file URLs)
    AWS_S3_CUSTOM_DOMAIN = f'{AWS_STORAGE_BUCKET_NAME}.s3.us-west-002.backblazeb2.com'
    
    # B2-specific: Don't use virtual-hosted style addressing
    AWS_S3_USE_SSL = True
    AWS_S3_VERIFY = True
    
    # B2-specific settings (B2 doesn't support ACLs like S3)
    # Remove ACL settings as B2 handles permissions differently
    AWS_DEFAULT_ACL = None  # B2 doesn't use ACLs
    AWS_QUERYSTRING_AUTH = True   # Adds signature to URLs for security
    AWS_S3_FILE_OVERWRITE = True  # Allow overwriting - B2 handles this differently
    AWS_S3_MAX_MEMORY_SIZE = 5242880  # 5MB
    AWS_S3_OBJECT_PARAMETERS = {
        'CacheControl': 'max-age=86400',  # Cache for 1 day
    }
    
    # B2 requires signature version 4
    AWS_S3_SIGNATURE_VERSION = 's3v4'
    
    # Disable addressing style (B2 uses path-style by default)
    AWS_S3_ADDRESSING_STYLE = 'path'
    
    # Use B2 for media files with custom backend
    STORAGES = {
        'default': {
            'BACKEND': 'config.storage_backends.B2Storage',
        },
        'staticfiles': {
            'BACKEND': 'django.contrib.staticfiles.storage.StaticFilesStorage',
        },
    }
    
    # Media URL configuration for B2
    MEDIA_URL = f'https://{AWS_S3_CUSTOM_DOMAIN}/'
    MEDIA_ROOT = ''  # Not used when using S3
else:
    # Use local storage if B2 credentials not provided
    MEDIA_URL = '/media/'
    MEDIA_ROOT = os.path.join(BASE_DIR, 'media')