"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 4.2.19.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os
import re
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load .env file from project root
env_path = BASE_DIR / '.env'
if env_path.exists():
    # Check if system env vars exist (they override .env)
    b2_access_key_system = os.environ.get('B2_ACCESS_KEY', '')
    b2_secret_key_system = os.environ.get('B2_SECRET_KEY', '')
    
    if b2_access_key_system or b2_secret_key_system:
        print(f"⚠️  WARNING: System environment variables found for B2 credentials!")
        print(f"   System B2_ACCESS_KEY: {'SET' if b2_access_key_system else 'NOT SET'} (length: {len(b2_access_key_system)})")
        print(f"   System B2_SECRET_KEY: {'SET' if b2_secret_key_system else 'NOT SET'} (length: {len(b2_secret_key_system)})")
        print(f"   System env vars override .env file values!")
        print(f"   To use .env file, unset system variables or remove them from your shell profile")
    
    load_dotenv(dotenv_path=env_path, override=True)  # Override system vars with .env file
    print(f"✅ Loaded .env file from: {env_path}")
else:
    # Fallback to default behavior (current directory)
    load_dotenv()
    print(f"⚠️  .env file not found at {env_path}, trying current directory...")

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure--*)3pd+&c*76gnikyo^(rnz!ivf&iy!k1z4w$l(4!$ekc0*p$8')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    'topsoftware.tech', 
    'www.topsoftware.tech',
    'localhost',
    '127.0.0.1',
    '192.168.1.203',  # Your local IP address
    'topsoftware-website-1c184caef3c1.herokuapp.com',
]

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_recaptcha',
    
    # Local apps
    'contact',
    'home',
    'pricing',
    'portfolio',
    'payments',
    'sales_application',

    # Installed third-party apps
    'corsheaders',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    "config.middleware.EnforceDomainMiddleware"
]

CSRF_TRUSTED_ORIGINS = [
    "https://www.topsoftware.tech",
    "http://localhost:8000",
    "http://127.0.0.1:8000"
]
CSRF_COOKIE_SECURE = not DEBUG  # Only use secure cookies in production

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(BASE_DIR, 'navigationmain'),
            os.path.join(BASE_DIR, 'home', 'templates'),
            os.path.join(BASE_DIR, 'contact', 'templates'),
            os.path.join(BASE_DIR, 'pricing', 'templates'),
            os.path.join(BASE_DIR, 'portfolio', 'templates'),
            os.path.join(BASE_DIR, 'payments', 'templates'),
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
    os.path.join(BASE_DIR, 'home', 'static'),
    os.path.join(BASE_DIR, 'contact', 'static'),
    os.path.join(BASE_DIR, 'pricing', 'static'),
    os.path.join(BASE_DIR, 'portfolio', 'static'),
    os.path.join(BASE_DIR, 'payments', 'static'),
]

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Email Configuration - Using Environment Variables for Security
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = "officialtopsoftware@gmail.com"
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', "")

# Square Configuration
SQUARE_LOCATION_ID = os.getenv('SQUARE_LOCATION_ID', "")

# CORS Settings
CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_METHODS = ["GET", "POST", "OPTIONS", "PUT", "DELETE"]
CORS_ALLOWED_ORIGINS = [
    "http://localhost:8000",
    "http://127.0.0.1:8000",
]

# Stripe Settings - Using Environment Variables for Security
STRIPE_PUBLISHABLE_KEY = os.getenv('STRIPE_PUBLISHABLE_KEY', '')
STRIPE_SECRET_KEY = os.getenv('STRIPE_SECRET_KEY', '')
STRIPE_WEBHOOK_SECRET = os.getenv('STRIPE_WEBHOOK_SECRET', '')

# reCAPTCHA Settings - Using Environment Variables for Security
RECAPTCHA_PUBLIC_KEY = os.getenv('RECAPTCHA_PUBLIC_KEY', '')
RECAPTCHA_PRIVATE_KEY = os.getenv('RECAPTCHA_PRIVATE_KEY', '')
RECAPTCHA_DOMAIN = 'www.recaptcha.net'

# Media files (Uploaded files)
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

FILE_UPLOAD_MAX_MEMORY_SIZE = 5242880  # 5MB
FILE_UPLOAD_PERMISSIONS = 0o644
FILE_UPLOAD_HANDLERS = [
    'django.core.files.uploadhandler.MemoryFileUploadHandler',
    'django.core.files.uploadhandler.TemporaryFileUploadHandler',
]

# Backblaze B2 Configuration
# Application Key ID: 0046d1240f581bd0000000006
# Key Name: resumekey
# Bucket Name: topsoftwareresumes
# Bucket ID: 062de1c28440bff598b10b1d
# IMPORTANT: Make sure these environment variables are set in your .env file:
#   B2_ACCESS_KEY=0046d1240f581bd0000000006  (or B2_KEY_ID as fallback)
#   B2_SECRET_KEY=<your-secret-key>  (or B2_APPLICATION_KEY as fallback)
#   B2_BUCKET_NAME=topsoftwareresumes
# Strip whitespace and clean credentials to prevent "malformed credential" errors
# Support both naming conventions for backward compatibility
def clean_credential(value):
    """Clean credential value by removing quotes, whitespace, and newlines"""
    if not value:
        return ''
    # Convert to string if not already
    value = str(value)
    # Remove surrounding quotes (single or double)
    value = value.strip().strip('"').strip("'")
    # Remove any newlines, carriage returns, and tabs
    value = value.replace('\n', '').replace('\r', '').replace('\t', '')
    # Remove any remaining whitespace
    value = value.strip()
    # Remove any non-printable characters (more aggressive cleaning)
    value = ''.join(c for c in value if c.isprintable())
    return value

# Get raw values first for debugging
raw_b2_access_key = os.getenv('B2_ACCESS_KEY', '')
raw_b2_key_id = os.getenv('B2_KEY_ID', '')
raw_b2_secret_key = os.getenv('B2_SECRET_KEY', '')
raw_b2_app_key = os.getenv('B2_APPLICATION_KEY', '')

# Debug: Show what we're reading from environment
print(f"\n🔍 Environment Variable Debug:")
print(f"   B2_ACCESS_KEY from env: {'SET' if raw_b2_access_key else 'NOT SET'} (length: {len(raw_b2_access_key)})")
if raw_b2_access_key:
    print(f"   B2_ACCESS_KEY value: {raw_b2_access_key[:10]}...{raw_b2_access_key[-4:] if len(raw_b2_access_key) > 14 else raw_b2_access_key}")
print(f"   B2_KEY_ID from env: {'SET' if raw_b2_key_id else 'NOT SET'} (length: {len(raw_b2_key_id)})")
print(f"   B2_SECRET_KEY from env: {'SET' if raw_b2_secret_key else 'NOT SET'} (length: {len(raw_b2_secret_key)})")
if raw_b2_secret_key:
    print(f"   B2_SECRET_KEY value: {raw_b2_secret_key[:10]}...{raw_b2_secret_key[-4:] if len(raw_b2_secret_key) > 14 else raw_b2_secret_key}")
print(f"   B2_APPLICATION_KEY from env: {'SET' if raw_b2_app_key else 'NOT SET'} (length: {len(raw_b2_app_key)})")
print()

B2_KEY_ID = clean_credential(raw_b2_access_key or raw_b2_key_id)
B2_SECRET_KEY = clean_credential(raw_b2_secret_key or raw_b2_app_key)

# Validate credential format - CRITICAL CHECKS
credential_error = False
error_messages = []

if B2_KEY_ID and B2_KEY_ID.startswith('K'):
    error_messages.append("❌ CRITICAL: B2_KEY_ID (B2_ACCESS_KEY) appears to be a Secret Key (starts with 'K')!")
    error_messages.append("   B2 Key IDs should be 24 characters and start with NUMBERS")
    error_messages.append("   Example: 0046d1240f581bd0000000006")
    credential_error = True

if B2_KEY_ID and (len(B2_KEY_ID) < 24 or len(B2_KEY_ID) > 25):
    error_messages.append(f"❌ CRITICAL: B2_KEY_ID length is {len(B2_KEY_ID)}, expected 24-25 characters")
    error_messages.append(f"   Current value: {B2_KEY_ID[:10]}...{B2_KEY_ID[-4:]}")
    credential_error = True

if B2_SECRET_KEY and not B2_SECRET_KEY.startswith('K'):
    error_messages.append("❌ CRITICAL: B2_SECRET_KEY doesn't start with 'K'!")
    error_messages.append("   B2 Secret Keys must start with 'K' and be 25-50 characters long")
    credential_error = True

if B2_SECRET_KEY and len(B2_SECRET_KEY) < 25:
    error_messages.append(f"❌ CRITICAL: B2_SECRET_KEY length is {len(B2_SECRET_KEY)}, expected 25-50 characters")
    error_messages.append(f"   Current value: {B2_SECRET_KEY[:10]}...{B2_SECRET_KEY[-4:]}")
    credential_error = True

if credential_error:
    print("\n" + "="*70)
    print("🚨 B2 CREDENTIAL CONFIGURATION ERROR 🚨")
    print("="*70)
    for msg in error_messages:
        print(msg)
    print("\n📋 HOW TO FIX:")
    print("   1. Go to your Backblaze B2 dashboard")
    print("   2. Navigate to: App Keys (or Application Keys)")
    print("   3. Find your Application Key and copy:")
    print("      - Application Key ID (24-25 chars, starts with numbers) → B2_ACCESS_KEY")
    print("      - Application Key (Secret, 25-50 chars, starts with K) → B2_SECRET_KEY")
    print("\n   Your .env file should look like:")
    print("   B2_ACCESS_KEY=0046d1240f581bd0000000006")
    print("   B2_SECRET_KEY=K0047/6/y1C+VybVzGLLcaqGDSFeG3M")
    print("   B2_BUCKET_NAME=topsoftwareresumes")
    print("   B2_ENDPOINT_URL=https://s3.us-west-002.backblazeb2.com")
    print("\n   ⚠️  Make sure:")
    print("      - No quotes around values")
    print("      - No spaces around = sign")
    print("      - Each value on a single line")
    print("="*70 + "\n")
    
    # Don't raise an error here, just warn - let them see the full error
    # But make it very clear what's wrong
B2_BUCKET_NAME = clean_credential(os.getenv('B2_BUCKET_NAME', ''))
B2_ENDPOINT_URL = clean_credential(os.getenv('B2_ENDPOINT_URL', 'https://s3.us-west-002.backblazeb2.com'))

# Debug print with detailed validation
print(f"DEBUG - B2_KEY_ID: {'SET' if B2_KEY_ID else 'NOT SET'}")
if B2_KEY_ID:
    print(f"DEBUG - B2_KEY_ID value: {B2_KEY_ID[:10]}...{B2_KEY_ID[-4:] if len(B2_KEY_ID) > 14 else B2_KEY_ID}")
    print(f"DEBUG - B2_KEY_ID length: {len(B2_KEY_ID)} chars")
    # B2 Key IDs are typically 24-25 characters
    if len(B2_KEY_ID) < 24 or len(B2_KEY_ID) > 25:
        print(f"⚠️  WARNING - B2_KEY_ID length is {len(B2_KEY_ID)}, expected 24-25 characters")
else:
    print("❌ ERROR - B2_KEY_ID is NOT SET! Check your .env file for B2_ACCESS_KEY or B2_KEY_ID")

print(f"DEBUG - B2_SECRET_KEY: {'SET' if B2_SECRET_KEY else 'NOT SET'}")
if B2_SECRET_KEY:
    print(f"DEBUG - B2_SECRET_KEY length: {len(B2_SECRET_KEY)} chars")
    # B2 Secret Keys are typically 25-50 characters
    if len(B2_SECRET_KEY) < 25:
        print(f"⚠️  WARNING - B2_SECRET_KEY length is {len(B2_SECRET_KEY)}, seems too short (expected 25-50)")
else:
    print("❌ ERROR - B2_SECRET_KEY is NOT SET! Check your .env file for B2_SECRET_KEY or B2_APPLICATION_KEY")

print(f"DEBUG - B2_BUCKET_NAME: {B2_BUCKET_NAME if B2_BUCKET_NAME else 'NOT SET'}")
if not B2_BUCKET_NAME:
    print("❌ ERROR - B2_BUCKET_NAME is NOT SET!")

# Check if we should use B2
USE_B2_STORAGE = bool(B2_KEY_ID and B2_SECRET_KEY and B2_BUCKET_NAME)

if USE_B2_STORAGE:
    print("✅ Using Backblaze B2 storage")
    
    # Add storages to INSTALLED_APPS
    if 'storages' not in INSTALLED_APPS:
        INSTALLED_APPS.append('storages')
    
    # AWS/B2 Settings - MUST use these exact variable names
    # Ensure credentials are clean and valid before setting
    if not B2_KEY_ID or not B2_SECRET_KEY:
        raise ValueError("B2_KEY_ID and B2_SECRET_KEY must be set in environment variables")
    
    # Additional validation: ensure no hidden characters
    if '\n' in B2_KEY_ID or '\r' in B2_KEY_ID or '\t' in B2_KEY_ID:
        print("⚠️  WARNING - B2_KEY_ID contains newlines or tabs, cleaning...")
        B2_KEY_ID = B2_KEY_ID.replace('\n', '').replace('\r', '').replace('\t', '')
    
    if '\n' in B2_SECRET_KEY or '\r' in B2_SECRET_KEY or '\t' in B2_SECRET_KEY:
        print("⚠️  WARNING - B2_SECRET_KEY contains newlines or tabs, cleaning...")
        B2_SECRET_KEY = B2_SECRET_KEY.replace('\n', '').replace('\r', '').replace('\t', '')
    
    # Final credential validation and assignment
    # Print actual values (partially masked) for debugging
    print(f"🔑 B2 Credentials Summary:")
    print(f"   Key ID: {B2_KEY_ID[:6]}...{B2_KEY_ID[-4:] if len(B2_KEY_ID) > 10 else B2_KEY_ID} (length: {len(B2_KEY_ID)})")
    print(f"   Secret: {B2_SECRET_KEY[:6]}...{B2_SECRET_KEY[-4:] if len(B2_SECRET_KEY) > 10 else B2_SECRET_KEY} (length: {len(B2_SECRET_KEY)})")
    print(f"   Bucket: {B2_BUCKET_NAME}")
    
    # Check for common issues
    if len(B2_KEY_ID) < 24 or len(B2_KEY_ID) > 25:
        print(f"⚠️  WARNING: Key ID length is {len(B2_KEY_ID)}, expected 24-25")
    if len(B2_SECRET_KEY) < 25:
        print(f"⚠️  WARNING: Secret key length is {len(B2_SECRET_KEY)}, seems short (expected 25-50)")
    
    # Check for problematic characters
    problematic_chars = ['\n', '\r', '\t', '"', "'"]
    for char in problematic_chars:
        if char in B2_KEY_ID:
            print(f"⚠️  WARNING: Key ID contains problematic character: {repr(char)}")
        if char in B2_SECRET_KEY:
            print(f"⚠️  WARNING: Secret key contains problematic character: {repr(char)}")
    
    AWS_ACCESS_KEY_ID = B2_KEY_ID  # ← FIXED: Must be AWS_ACCESS_KEY_ID
    AWS_SECRET_ACCESS_KEY = B2_SECRET_KEY
    AWS_STORAGE_BUCKET_NAME = B2_BUCKET_NAME
    
    # Backblaze B2 endpoint configuration
    # AWS_S3_ENDPOINT_URL should be the bucket endpoint (e.g., https://s3.us-west-002.backblazeb2.com)
    AWS_S3_ENDPOINT_URL = B2_ENDPOINT_URL
    
    # AWS_S3_CUSTOM_DOMAIN format: bucket-name.bucket-endpoint
    # Extract the bucket endpoint from the endpoint URL (remove https://)
    bucket_endpoint = AWS_S3_ENDPOINT_URL.replace('https://', '').replace('http://', '')
    AWS_S3_CUSTOM_DOMAIN = f'{AWS_STORAGE_BUCKET_NAME}.{bucket_endpoint}'
    
    print(f"✅ B2 Configuration:")
    print(f"   Endpoint URL: {AWS_S3_ENDPOINT_URL}")
    print(f"   Custom Domain: {AWS_S3_CUSTOM_DOMAIN}")
    print(f"   Bucket: {AWS_STORAGE_BUCKET_NAME}")
    
    # B2-specific: Don't use virtual-hosted style addressing
    AWS_S3_USE_SSL = True
    AWS_S3_VERIFY = True
    
    # B2-specific settings (B2 doesn't support ACLs like S3)
    # Remove ACL settings as B2 handles permissions differently
    AWS_DEFAULT_ACL = None  # B2 doesn't use ACLs
    AWS_QUERYSTRING_AUTH = True   # Adds signature to URLs for security
    AWS_S3_FILE_OVERWRITE = True  # Allow overwriting - B2 handles this differently
    AWS_S3_MAX_MEMORY_SIZE = 5242880  # 5MB
    AWS_S3_OBJECT_PARAMETERS = {
        'CacheControl': 'max-age=86400',  # Cache for 1 day
    }
    
    # B2 requires signature version 4
    AWS_S3_SIGNATURE_VERSION = 's3v4'
    
    # B2 uses path-style addressing (not virtual-hosted)
    AWS_S3_ADDRESSING_STYLE = 'path'
    
    # Use B2 for media files with custom backend
    STORAGES = {
        'default': {
            'BACKEND': 'config.storage_backends.B2Storage',
        },
        'staticfiles': {
            'BACKEND': 'django.contrib.staticfiles.storage.StaticFilesStorage',
        },
    }
    
    # Media URL configuration for B2
    MEDIA_URL = f'https://{AWS_S3_CUSTOM_DOMAIN}/'
    MEDIA_ROOT = ''  # Not used when using S3
else:
    # Use local storage if B2 credentials not provided
    MEDIA_URL = '/media/'
    MEDIA_ROOT = os.path.join(BASE_DIR, 'media')